// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxIUKH_nTGUSwe_SBuig03ItqdPQxI6rY',
    appId: '1:720084397751:android:efe85cb369c5611e3ee732',
    messagingSenderId: '720084397751',
    projectId: 'expertisemarket-67626',
    storageBucket: 'expertisemarket-67626.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFfaIcXS8Okv3QfvJpx1Y6vzBLymoLgU',
    appId: '1:720084397751:ios:b7a05d84df4fc3923ee732',
    messagingSenderId: '720084397751',
    projectId: 'expertisemarket-67626',
    storageBucket: 'expertisemarket-67626.firebasestorage.app',
    androidClientId: '720084397751-tqvodt2vcr45mb573ejlut7an5m99905.apps.googleusercontent.com',
    iosClientId: '720084397751-ab750duk107tv6a7p4a5ocmqaiqrgs67.apps.googleusercontent.com',
    iosBundleId: 'com.CraftMarket',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTpvx0vM0_xhsEWJOKvSeDzo5das18NM',
    appId: '1:720084397751:web:7e95a7066f05fac43ee732',
    messagingSenderId: '720084397751',
    projectId: 'expertisemarket-67626',
    authDomain: 'expertisemarket-67626.firebaseapp.com',
    storageBucket: 'expertisemarket-67626.firebasestorage.app',
    measurementId: 'G-YH0PXLZ9X3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFfaIcXS8Okv3QfvJpx1Y6vzBLymoLgU',
    appId: '1:720084397751:ios:b7a05d84df4fc3923ee732',
    messagingSenderId: '720084397751',
    projectId: 'expertisemarket-67626',
    storageBucket: 'expertisemarket-67626.firebasestorage.app',
    androidClientId: '720084397751-tqvodt2vcr45mb573ejlut7an5m99905.apps.googleusercontent.com',
    iosClientId: '720084397751-ab750duk107tv6a7p4a5ocmqaiqrgs67.apps.googleusercontent.com',
    iosBundleId: 'com.CraftMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTpvx0vM0_xhsEWJOKvSeDzo5das18NM',
    appId: '1:720084397751:web:a01067066cff4c753ee732',
    messagingSenderId: '720084397751',
    projectId: 'expertisemarket-67626',
    authDomain: 'expertisemarket-67626.firebaseapp.com',
    storageBucket: 'expertisemarket-67626.firebasestorage.app',
    measurementId: 'G-DZ570ZWMY8',
  );
}
